@User.Api_HostAddress = https://localhost:7244

GET {{user.api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{User.Api_HostAddress}}/api/v1/token
Content-Type: application/json

{
 "Username":"test",
 "Password":"test"
}

###

GET {{User.Api_HostAddress}}/api/user/UserTypes

###

GET {{User.Api_HostAddress}}/api/user/UserTypes

###

GET {{User.Api_HostAddress}}/api/user/UserTypes

###

POST {{User.Api_HostAddress}}/api/user/token
Content-Type: application/json

{
    "username":99899269658,
    "password":"dsda"
}

###

@pageNumber=1
@pagesize=10
GET {{User.Api_HostAddress}}/api/user/getUsers?pageNumber={{pageNumber}}&pagesize={{pagesize}}

###

GET {{User.Api_HostAddress}}/api/user/getUsers?pageNumber={{pageNumber}}&pagesize={{pagesize}}

###

POST {{User.Api_HostAddress}}/api/user/AddUser
Content-Type: application/json

{
  //AddUserMasterCommand
}

###

POST {{User.Api_HostAddress}}/api/user/UpdateUser
Content-Type: application/json

{
  //AddUserMasterCommand
}

###

GET {{User.Api_HostAddress}}/api/country

###


@id=0
GET {{User.Api_HostAddress}}/api/city?id={{id}}

###

GET {{User.Api_HostAddress}}/api/state?id={{1}}

###

GET {{User.Api_HostAddress}}/api/state?id={{id}}

###

GET {{User.Api_HostAddress}}/api/company?pageNumber={{pageNumber}}&pagesize={{pagesize}}

###

POST {{User.Api_HostAddress}}/api/company
Content-Type: application/json

{
  //AddCompanyCommand
}

###

GET {{User.Api_HostAddress}}/api/productcategory?pageNumber={{pageNumber}}&pagesize={{pagesize}}

###
